export const animalsIcon = [
  'haibao.png',
  'keji.png',
  'ji.png',
  'lu.png',
  'mao.png',
  'laohu.png',
  'xiong.png',
  'ma.png',
  'luozi.png',
  'ya.png',
  'lang.png',
  'yang.png',
  'bao.png',
  'buzhidao.png',
  'niu.png',
  'xx.png',
  'she.png',
  'lv.png',
  'mao.png',
  'shanyang.png',
];

export const foods = [
  'food.png',
  'food_1.png',
  'food_2.png',
  'food_3.png',
  'food_4.png',
  'food_5.png',
  'food_6.png',
  'food_7.png',
  'food_8.png',
  'food_9.png',
  'food_10.png',
  'food_11.png',
  'food_12.png',
  'food_13.png',
  'food_14.png',
  'food_15.png',
  'food_16.png',
  'food_17.png',
  'food_18.png',
  'food_19.png',
];

export const lingshi = [
  'icon.png',
  'icon_1.png',
  'icon_2.png',
  'icon_3.png',
  'icon_4.png',
  'icon_5.png',
  'icon_6.png',
  'icon_7.png',
  'icon_8.png',
  'icon_9.png',
  'icon_10.png',
  'icon_11.png',
  'icon_12.png',
  'icon_13.png',
  'icon_14.png',
  'icon_15.png',
  'icon_16.png',
  'icon_17.png',
  'icon_18.png',
  'icon_19.png',
];

export const lingshiIcon = [
  'img.png',
  'img_1.png',
  'img_2.png',
  'img_3.png',
  'img_4.png',
  'img_5.png',
  'img_6.png',
  'img_7.png',
  'img_8.png',
  'img_9.png',
  'img_10.png',
  'img_11.png',
  'img_12.png',
  'img_13.png',
  'img_14.png',
  'img_15.png',
  'img_16.png',
  'img_17.png',
  'img_18.png',
  'img_19.png',
];

export const IconEmun: any = {
  animalsIcon: animalsIcon,
  foods: foods,
  lingshi: lingshi,
  lingshiIcon: lingshiIcon,
};
